CREATE TABLE MSTR_CLIENT_COUNTRY_ANALYSIS
(
	SSOID VARCHAR(1000),
    CLIENT varchar(500),
    COUNTRY_NAME varchar(500),
	SENTIMENT_SCORE NUMBER,
	NON_RESPONDED_USER_COUNT NUMBER,
	HOUR NUMBER,
    DAY NUMBER,
	MONTH NUMBER,
	YEAR NUMBER
);
