CREATE TABLE MSTR_HASHTAG_COUNTRY_ANALYSIS
(
	SSOID VARCHAR(1000),
    COUNTRY_NAME varchar(500),
    HASHTAG varchar(500),
	SENTIMENT_SCORE NUMBER,
	NUM_OF_USERS NUMBER,
    DAY NUMBER,
	MONTH NUMBER,
	YEAR NUMBER
);
